export const BUILD_COMMIT_MESSAGE = 'PLACEHOLDER_BUILD_COMMIT_MESSAGE';
export const BUILD_JOB = 'PLACEHOLDER_BUILD_JOB';
export const BUILD_COMMIT = 'PLACEHOLDER_BUILD_COMMIT'
export const BUILD_DATE = 'PLACEHOLDER_BUILD_DATE'