image: node:latest

pipelines:
  default:
    - step: 
      caches:
        - node
      script:
        - npm install -g firebase-tools
        # - cd /builds/kvasbo/tellulf-client
        - yarn install --non-interactive --pure-lockfile
        - CI=false yarn run build
        - firebase deploy --non-interactive --token $FIREBASE_DEPLOY_KEY